### ISSUE TITLE
Creo que hay un error en el dato de Aragón 2020-02-28 y Galicia 2020-03-12 nº de casos

### ISSUE THREAD

**Issue by numeroteca** [datadista/datasets#1]
No puede ser que el valor de casos acumulados sea `1` el  2020-02-28 y `0` al día siguiente (2020-03-02).

En Galicia bajan de `39` a `35` entre 03-11 y 03-12.

Ya de paso pregunto ¿De dónde sale ese dato de Aragón? No lo encuentro en los PDF originales del Ministerio. La primera fecha para datos de comunidades autónomas es de

**Comment by adelgadob** [comment]
El error de Aragón detectado ya ha sido comprobado y solucionado. Es un positivo que anunció Sanidad el 28 y luego resultó negativo. Por eso lo eliminaron al día siguiente.

**Comment by PARODBE** [comment]
Buenas! Me llamo Pablo, estoy terminando un máster de data scientist, soy nuevo en GITHUB, podeis activarme para poder descargarme los datos porfa?

Gracias!
Pablo

**Comment by JJ** [comment]
Descárgate git (o un GUI para él a tu plataforma), y copia lo que pone cuando pulsas el botón de "Clone" o directamente 

    git clone https://github.com/datadista/datasets

**Comment by JJ** [comment]
Also, dinos dónde estás haciendo el máster de ciencia de datos donde no explican git ni GitHub, por favor. Es para un amigo.

**Comment by PARODBE** [comment]
Hola!

estoy haciendolo en Madrid, en MBIT, y la verdad es que no hemos trabajado con GITHUB, y mira que hemos dado: estadistica, machine learning, series temporales, AWS, SQL...
________________________________
De: Juan Julián Merelo Guervós <notifications@github.com>
Enviado: jueves, 19 de marzo de 2020 17:46
Para: datadista/datasets <datasets@noreply.github.com>
Cc: Pablo Rodríguez Belenguer <pablo.rodriguez@mbitschool.com>; Comment <comment@noreply.github.com>
Asunto: Re: [datadista/datasets] Creo que hay un error en el dato de Aragón 2020-02-28 y Galicia 2020-03-12 nº de casos (#1)


Also, dinos dónde estás haciendo el máster de ciencia de datos donde no explican git ni GitHub, por favor. Es para un amigo.

**Comment by adelgadob** [comment]
También puedes descargarlo directamente desde la web entrando en la opción "raw" de cada archivo.

Ej: https://raw.githubusercontent.com/datadista/datasets/master/COVID%2019/nacional_covid19.csv

**Comment by JJ** [comment]
El jue., 19 mar. 2020 a las 20:08, PARODBE (<notifications@github.com>)
escribió:

> Hola!
>
> estoy haciendolo en Madrid, en MBIT, y la verdad es que no hemos trabajado
> con GITHUB, y mira que hemos dado: estadistica, machine learning, series
> temporales, AWS, SQL...
>

Si necesitas ayuda no tienes más que preguntar. Preo créeme, saber git y
GitHub (o GitLab) es imprescindible en ciencia de datos o cualquier otra
cosa que incluya informática.

**Comment by xabitrigo** [comment]
> El error de Aragón detectado ya ha sido comprobado y solucionado. Es un positivo que anunció Sanidad el 28 y luego resultó negativo. Por eso lo eliminaron al día siguiente.

Sabéis cuál es el motivo "extraño" de Galicia?

**Comment by adelgadob** [comment]
Cierro este issue ya que ha sido corregido con la serie histórica del ISCIII a fecha 2020-05-01
