### ISSUE TITLE
Catalunya, salto de casos acumulados del día 9 al 10 de mayo

### ISSUE THREAD

**Issue by ghost** [datadista/datasets#100]
Hola,
En la serie de casos por CCAA, en Catalunya, del día 9 al día 10 hay un salto de 2942 casos.
53578 | 56520
-- | --
¿Se trata de una actualización de casos antiguos?
Muchas gracias

**Comment by adelgadob** [comment]
Por favor, lea las notas que se añaden periódicamente al Readme antes de abrir un issue.

**Comment by ghost** [comment]
Disculpe.
