### ISSUE TITLE
why is ccaa_covid19_altas.csv / ccaa_covid19_casos.csv / ccaa_covid19_fallecidos.csv not being updated?

### ISSUE THREAD

**Issue by dexiantac** [datadista/datasets#103]

**Comment by adelgadob** [comment]
Because the Ministry of Health has not been offering these for two days

**Comment by adelgadob** [comment]
ccaa_covid19_fallecidos.csv has been updated
ccaa_covid19_altas.csv and ccaa_covid19_confirmados_test.csv not yet because the Ministry of Health has not been offering these from two days

ccaa_covid19_casos.csv is a sum from ccaa_covid19_confirmados_test.csv and ccaa_covid19_confirmados_prc.csv

**Comment by dexiantac** [comment]
Thank you very much for the reply.
