### ISSUE TITLE
Ausencia de dos días en: nacional_covid19.csv

### ISSUE THREAD

**Issue by CarlaRom** [datadista/datasets#109]
Hola!

Antes que nada, me gustaría daros las gracias por todo el trabajo de recolección, limpieza, análisis y actualización de datos que estais llevando a cabo. ¡Es impresionante! Sois un gran referente .

En el fichero **nacional_covid9.csv** faltan los días: **2020-07-04** y **2020-07-05**.  A partir del día 2020-07-03 hay un salto al día 2020-07-06.

Un saludo.

**Comment by adelgadob** [comment]
El Ministerio de Sanidad ha dejado de publicar datos los fines de semana

**Comment by CarlaRom** [comment]
De acuerdo, muchas gracias.
