### ISSUE TITLE
Nacional Covid 19

### ISSUE THREAD

**Issue by diophantus287** [datadista/datasets#117]
En la serie nacional_covid19.csv está repetida la línea 205 (9 de octubre). Ayer hice una proposición de edición para quitarla pero no se aceptó. Haré otra ahora para ver si se puede aceptar, porque lleva así unos días y supongo que hay más gente a la que le está dando problemas como a mí.

**Comment by adelgadob** [comment]
No llegó ninguna pull request, pero lo arreglamos nosotros. Gracias
