### ISSUE TITLE
Dar contexto espacial a los datos

### ISSUE THREAD

**Issue by hhkaos** [datadista/datasets#121]
**UPDATE**

Perdón... acabo de ver [CONTRIBUTING.md](https://github.com/datadista/datasets/blob/master/CONTRIBUTING.md), y en [datadista/datasets/COVID%2019](https://github.com/datadista/datasets/tree/master/COVID%2019) he visto varias cosas como un [repo de Ramiro](https://github.com/ramiroaznar/covid19-to-tinybird) y que hay datos como [ccaa_covid19_datos_sanidad_nueva_serie.csv](https://raw.githubusercontent.com/datadista/datasets/master/COVID%2019/ccaa_covid19_datos_sanidad_nueva_serie.csv) que ya tienen un código INE. Yo estaba mirando concretamente [ccaa_vacunas.csv](https://raw.githubusercontent.com/datadista/datasets/master/COVID%2019/ccaa_vacunas.csv) (de ahí la pregunta).

Por tanto mi pregunta es... se puede contribuir a los scripts que generan los datos? Es que no sé si están publicados (o no los encuentro), perdón por la ignorancia.

---

Buenas!, lo primero de todo **sumarme a los agradecimientos** por el trabajo que realizáis.

Lo segundo que quería preguntar es si hay alguna forma de contribuir. 

Si fuese posible me gustaría añadir el [código INE](https://www.ine.es/daco/daco42/codmun/cod_ccaa.htm) a los datos de las comunidades y las provincias. Y lo siguiente sería intentar generar un fichero GeoJSON (además del CSV) para facilitar las representaciones visuales (en mapas) de estos datos.

Gracias!!,
Raúl

P.D: dejo un ejemplo de CSV que incluye el código INE de cada CCAA con el nombre que usáis en vuestro dataset.

```csv
cod_CCAA,Nombre Name,INSPIREID,NATCODE
1,Andalucía,ES.IGN.SIGLIM34010000000,34010000000
2,Aragón,ES.IGN.SIGLIM34020000000,34020000000
3,Asturias,ES.IGN.SIGLIM34030000000,34030000000
4,Baleares,ES.IGN.SIGLIM34040000000,34040000000
5,Canarias,ES.IGN.SIGLIM34050000000,34050000000
6,Cantabria,ES.IGN.SIGLIM34060000000,34060000000
7,Castilla y Leon,ES.IGN.SIGLIM34070000000,34070000000
8,Castilla La Mancha,ES.IGN.SIGLIM34080000000,34080000000
9,Cataluña,ES.IGN.SIGLIM34090000000,34090000000
10,C. Valenciana,ES.IGN.SIGLIM34100000000,34100000000
11,Extremadura,ES.IGN.SIGLIM34110000000,34110000000
12,Galicia,ES.IGN.SIGLIM34120000000,34120000000
13,Madrid,ES.IGN.SIGLIM34130000000,34130000000
14,Murcia,ES.IGN.SIGLIM34140000000,34140000000
15,Navarra,ES.IGN.SIGLIM34150000000,34150000000
16,País Vasco,ES.IGN.SIGLIM34160000000,34160000000
17,La Rioja,ES.IGN.SIGLIM34170000000,34170000000
18,Ceuta,ES.IGN.SIGLIM34180000000,34180000000
19,Melilla,ES.IGN.SIGLIM34190000000,34190000000

**Comment by adelgadob** [comment]
Hola, vamos añadir el código INE al dataset de vacunas. En unos días estará disponible.

**Comment by adelgadob** [comment]
Ya está subida una nueva versión con una nueva columna denominada "cod_ine"
