### ISSUE TITLE
Error de estructura en `ccaa_vacunas.csv` al haber añadido el Ministerio nueva columna (entregadas AstraZeneca)

### ISSUE THREAD

**Issue by Pakillo** [datadista/datasets#122]
Hola,

Muchas gracias por el trabajazo que hacéis. 

Me parece que el dataset de `ccaa_vacunas.csv` presenta un error de estructura a partir de hoy (9 Febrero 2021) al haber añadido el Ministerio una nueva columna con las dosis entregas de AstraZeneca:

![image](https://user-images.githubusercontent.com/1597843/107447072-0d4a8a80-6b40-11eb-8bdf-ad0fc4c25153.png)

Podría intentar hacer un pull request actualizando la estructura de ese dataset, pero sospecho que hará falta actualizar también los scripts de extracción y ensamblaje de datos de vacunas...

Gracias

**Comment by adelgadob** [comment]
Hola, ya está corregido. Gracias por avisarnos.

**Comment by Pakillo** [comment]
¡Muchas gracias!
