### ISSUE TITLE
Fechas de cada ola

### ISSUE THREAD

**Issue by BiotechPedro** [datadista/datasets#123]
Muy buenas! 

Hay fechas concretas que se fijen para el inicio o final de cada ola? En caso negativo hay algún criterio concreto a partir del cual considerar como inicio o final de ola (por ejemplo, una IA a 14 días superior a 200)?

Gracias y enhorabuena por todos los dataset y artículos :D

**Comment by adelgadob** [comment]
No hay fechas concretas. Se suele usar los picos y valles en las olas. Nosotros usamos semanas para no definir un día concreto:  la primera ola estaría marcada entre las semanas 11 y 19; la segunda entre la semana 30 y la 49; la tercera a partir de la semana 50 de 2020.
