### ISSUE TITLE
No se actualizan los datos desde el día 8 de abril

### ISSUE THREAD

**Issue by beitaclemente** [datadista/datasets#125]
Los datos de series de COVID recogidos del ministerio de Sanidad llevan sin actualizar desde el día 8 de abril. ¿Es por algún error??

Gracias

**Comment by adelgadob** [comment]
Hola, si te refieres a las series que provienen el ISCIII, solo se actualizan de martes a viernes que es cuando el ISCIII actualiza la series históricas y generamos los diferentes datasets asociados a esas series.

**Comment by beitaclemente** [comment]
Muchas gracias por la info!
