### ISSUE TITLE
Inconsistencias del 9/3/2020

### ISSUE THREAD

**Issue by FcoJavT** [datadista/datasets#15]
Solo para que lo tengáis presente.
Según la actualización 39B (del 9/3/2020 a las 18.00), el número de casos en España es de 1204, pero en el informe correspondiente de la Organización Mundial de la Salud el número es 1024. Teniendo en cuenta que los demás días las cifras coinciden, es posible que haya habido un baile en los dígitos. Para saber cuál es el bueno habría que sumar los de las comunidades autónomas, pero el informe 39B no los aporta.
La OMS publica sus datos a las 10 a.m. CET, por lo que recoge los que publica España a las 18.00 del día anterior. (El informe de la OMS en cuestión es el 50, correspondiente a las 10 a.m. CET del 10 de marzo.)

![datos02](https://user-images.githubusercontent.com/58936176/76741947-aaeedb80-6770-11ea-92ee-3f60cb722ab6.jpg)

**Comment by adelgadob** [comment]
Los datos válidos son los del Ministerio de Sanidad ya que es la fuente original de la información a través del trabajo de recopilación de datos que realiza el CCAES
