### ISSUE TITLE
Los casos del día 8

### ISSUE THREAD

**Issue by JJ** [datadista/datasets#16]
¿No sería conveniente, aunque fuera por temas de complitud, poner como día 9 los del boletín 39B y como día 8 los del boletín 39?
También: ¿qué pasa con los datos del día 7?

**Comment by adelgadob** [comment]
No, porque los datos del boletín 39B son de las 18h  del 9 de marzo y son básicamente los mismos datos del 39 que se publicó el 9 de marzo a las 12h.

El fin de semana del 7 y 8 de abril no se publicaron informes por ser fin de semana y aún la situación no era de alarma. Por eso no hay datos. Creemos que esos datos  a nivel interno los tendrán el CCAES. Intentaremos conseguirlos.

**Comment by JJ** [comment]
¿Se podrían agregar los de las CCAEs?

**Comment by adelgadob** [comment]
Hemos añadido datos oficiales suministrados por Sanidad en su canal para periodistas de datos para los días 29  de febrero y 1, 7 y 8 de marzo.
