### ISSUE TITLE
datos desde el 16-03

### ISSUE THREAD

**Issue by FcoJavT** [datadista/datasets#24]
Perdonadme esta duda que me corroe.
Como sabéis, desde la actualización 47, los datos que se ofrecen son los consolidados a las 21h del día anterior. ¿No sería más fiel a la realidad asignar al día 16-03 11178 casos y seguir a partir de ahí? De modo que:
2020-03-17: 13716
2020-03-18: 17147
2020-03-19: 19980
Hasta ese cambio los datos sí se correspondían con el día del informe, aunque fuera hasta las 13h, pero ahora son justo los del día anterior.
¿O es que el informe que se publicaba a las 13h en realidad solo tenía datos del día anterior y hemos estado siempre con un día de desfase?

Gracias.

**Comment by adelgadob** [comment]
En la práctica parece que deben estar recibiendo datos hasta el mismo día por la mañana. No todas las CCAA están enviando datos de forma sistematizada.

**Comment by JJ** [comment]
Igual eso explica los efectos periódicos que se ven aquí:
https://twitter.com/jjmerelo/status/1240994595711995904

**Comment by FcoJavT** [comment]
¿Se están solapando datos?

**Comment by JJ** [comment]
> ¿Se están solapando datos?

No, ¿por?

**Comment by FcoJavT** [comment]
Nada. Me estaba obsesionando con la posibilidad de que se estén reportando por duplicado algunos eventos. Por ejemplo, un nuevo fallecimiento del 17 a las 9h aparecería en el informe publicado ese día (con, en principio, datos consolidados del 16) por haberse producido antes de las 13h y también en el informe publicado el día 18, con datos del 17, porque de hecho el fallecimiento se ha producido ese día 17. (En todo caso, en los datos acumulados entiendo que esto no afectaría.)
No sé si me explico. Igual es cosa mía, producto del encierro…

**Comment by JJ** [comment]
No debería... Yo creo que se consolidan los datos todos los días, pero que me corrija @adelgadob si me equivoco.

**Comment by adelgadob** [comment]
Se ha corregido la serie histórica con los datos del ISCIII con fecha 2020-05-01
