### ISSUE TITLE
Csv con fecha de últimas actualizaciones

### ISSUE THREAD

**Issue by Krato** [datadista/datasets#31]
Hola, muchas gracias por la info.

Estaría bien incluir un csv pra saber las últimas modificaiones de los archivos. De esa manera podríamos cargar solo los archivos que se han modificado:

Archivo | Fecha Modificacion
------- | -------------
ccaa_covid19_casos.csv | 2020-03-23 12:45:15
ccaa_covid19_altas.csv | 2020-03-23 11:30:00

El formato de fecha podría variar al que considerárais oportuno. La hora sería necesario.

¿Qué os parece?

**Comment by adelgadob** [comment]
Sí, se está preparando un cambio en el Readme para incluir toda esta información. Os pedimos paciencia.

**Comment by JJ** [comment]
Creo que esa información está disponible usando git o en el API de GitHub. Pero a ver si hay una forma más fácil de hacerlo.

**Comment by adelgadob** [comment]
Realizado gracias a la ayuda y trabajo de @JJ ¡Gracias!
Disponible aquí: https://github.com/datadista/datasets/blob/master/COVID%2019/fechas.md
