### ISSUE TITLE
Incongruencia de Datos Oficiales de Madrid 23/03/2020

### ISSUE THREAD

**Issue by DaniDSanj** [datadista/datasets#32]
Hola,

No sé si estoy haciendo mal los cálculos, por lo que os pido ayuda. En teoría, el número de casos activos (A) debería de ser A = Co - Cu - Fa, siendo "Co" los casos confirmados, "Cu" el número de curados y "Fa" el número de fallecidos. Para los datos de Madrid de 23/03/2020 (aunque pasa en más días) hay 7.249 casos activos. Sin embargo, dicen que hay 9.561 hospitalizados, lo cual no puede ser ya que el número es mayor que los propios activos. ¿Sabéis si estoy haciendo yo mal los cálculos o es un error del Ministerio de Sanidad?

Muchas gracias y un saludo,

**Comment by adelgadob** [comment]
Creemos que es un error de los datos enviados por Madrid a Sanidad. En la rueda de prensa de esta mañana le han preguntado directamente por ese error a Fernando Simón y no ha sabido explicarlo con claridad.

**Comment by DaniDSanj** [comment]
Muchas gracias por la rapidez y esperemos que puedan corregirlo próximamente.

Un saludo,

**Comment by DaniDSanj** [comment]
Para los datos del 24/03/2020 ha vuelto a ocurrir (8.526 Activos < 10.443 Hospitalizados). Llego a pensar que los datos de Madrid son hospitalizados históricos, porque me extraña que este error no se lo transmitan desde el Ministerio de forma inmediata.

**Comment by tekamolo** [comment]
También hay una incongruencia con los muertos de Madrid aparentemente. Sabéis algo de esto?
https://www.abc.es/espana/madrid/abci-madrid-reconoce-4275-muertos-mas-covid-19-gobierno-202004221705_noticia.html?fbclid=IwAR1eSaL-UzSdtLdrUjDBRg0GCZJu1sOfUy581kXysmHtIlxOBwaUD3gH-3o

**Comment by adelgadob** [comment]
Se ha corregido la serie histórica con los datos que la Comunidad de Madrid ha enviado a Sanidad y se ha incorporado a la serie que mantiene el ISCIII.
