### ISSUE TITLE
casos donde deberían estar altas

### ISSUE THREAD

**Issue by pedelriomarron** [datadista/datasets#34]
Creo que se ha sobrescrito casos en el archivo de altas, son  los mismos y los datos de altas son los de casos.
Gracias

https://github.com/datadista/datasets/blob/master/COVID%2019/ccaa_covid19_altas_long.csv

https://github.com/datadista/datasets/blob/master/COVID%2019/ccaa_covid19_casos_long.csv

**Comment by adelgadob** [comment]
Solucionado. ¡Gracias!
