### ISSUE TITLE
Column Data Format Changed

### ISSUE THREAD

**Issue by marcogiannuzzi90** [datadista/datasets#36]
Hello,

I just noticed that today all the column data changed format, previously was DD/MM/YYYY and now YYYY-MM-DD . Is it going to be this the new one?

Thanks,
Marco

**Comment by adelgadob** [comment]
Hello Marco,

Yes, it is a change to normalize the dataset in long format.  Also we have a new datasets organized by columns. the ending is "_long.csv"
