### ISSUE TITLE
definition of 'sexo' = 'ambos' in dataset nacional_covid19_rango_edad.csv

### ISSUE THREAD

**Issue by mvanreek** [datadista/datasets#38]
Could you give the definition of 'sexo' = 'ambos' in dataset nacional_covid19_rango_edad.csv?
Would it not be better to have just Male/Female/Unknown? To not double count Corona-cases.
Do you have a meta-data doc?

**Comment by adelgadob** [comment]
Fixed. Thanks!. and also we are working in a meta-data doc.
