### ISSUE TITLE
Evolución de casos UCI

### ISSUE THREAD

**Issue by Fojedaes** [datadista/datasets#39]
Buenas tardes,

Tenía la duda de si se conoce si los datos de ingresados en la UCI que se muestran las bases de datos son los acumulados o son los actualmente ingresados en la UCI. Muchas gracias.

**Comment by JJ** [comment]
Buena pregunta. No tengo ni idea. Yo estoy considerando que son los acumulados, pero es cierto que podrían ser los que hay ingresados en un momento determinado.

**Comment by adelgadob** [comment]
Sanidad ha aclarado hoy que los datos de hospitalizados y UCI que estaban facilitando son el acumulado de casos que han precisado hospitalización (incluyendo el dato de UCI) y casos que han precisado UCI. De hecho, han cambiado la denominación de los nombres de las columnas. También hemos actualizado el Readme para incluir esta información.
