### ISSUE TITLE
Datos variación total de fallecidos: datos agregados (con + sin covid)

### ISSUE THREAD

**Issue by GGPLOT9** [datadista/datasets#40]
Hola, 
Me pregunto si podría ayudarme a encontrar los datos de fallecidos totales en España o en una región concreta, durante una jornada determinada (por ejemplo ayer). Mi objetivo es poder medir la variabilidad de fallecimientos totales, es decir, cuánto está incrementando el número de fallecidos totales con respecto a la media de fallecidos, en lugar de con respecto a los casos detectados de Covid. ¿Podría ayudarme a obtener este dato? Gracias

**Comment by JJ** [comment]
Están en mi repo, https://github.com/covid-reports, en CSV y formato Rdata:
https://github.com/JJ/covid-reports/blob/master/covid-19-es.csv
Los suelo generar todos los días antes de comer.

**Comment by GGPLOT9** [comment]
Pero me parece que eso son los datos de fallecimientos CON coronavirus. Yo estoy buscando los datos de fallecimientos totales (con y sin), precisamente porque estoy tratando de cuantificar la variación con respecto al total de fallecidos.

**Comment by GGPLOT9** [comment]
La cuestión que me gustaría responder es ¿cuánta gente está muriendo de más con respecto al estadístico, es decir, con respecto a la media de fallecimientos?

**Comment by JJ** [comment]
Es la diferencia entre un día y el siguiente del dato de muertes por
coronavirus; está en la columna "Fallecimientos.Nuevos". ¿Qué quieres decir
con fallecimientos con y sin?

**Comment by JJ** [comment]
Ah. Ni idea. No sé si se publican esos datos cada día, por otro lado... Si
se hace, será en el INE, pero veo difícil que lo publiquen cada día.

**Comment by GGPLOT9** [comment]
Lo que me gustaría calcular es la variación total en el número de fallecidos. Es decir si la media diaria de fallecimientos (media estadística) es 1147 fallecimientos diarios, ¿cuánto ha incrementado esta cifra? Mi hipótesis es que los datos están registrando gran parte de fallecimientos cuya muerte no es imputable al coronavirus "per se", sino que son muertes con coronavirus, aunque hubiesen fallecido igualmente y por tanto, la variación de fallecimeintos con respecto a la media sería menor que el número de fallecidos CON COVID

**Comment by JJ** [comment]
Prefiero no discutir esa línea de argumentación. Pero sí es cierto que las
restricciones laborales y de movimiento seguro que han resultado en muchas
menos muertes. En todo caso, este repositorio entiendo que aloja los datos
relativos al coronavirus. Otro tipo de datos, como te he dicho antes,
estarán en el INE posiblemente y con la periodicidad que estimen
conveniente.

**Comment by adelgadob** [comment]
Esos datos solo se ofrecen firmando un NDA a investigadores. El INE cuando publique datos de mortalidad de 2020 será en 2021.

Más información: https://www.datanalytics.com/2020/03/12/monitorizacion-diaria-de-la-mortalidad/
