### ISSUE TITLE
Quitar totales de CSV

### ISSUE THREAD

**Issue by DasHammett** [datadista/datasets#41]
Se podrían eliminar las filas con totales de los CSV? Añaden pasos a la limpieza de datos, que se pueden agregar facilmente cuando se necesitan.

Gracias

**Comment by adelgadob** [comment]
Por nuestra parte ok, pero nos gustaría escuchar la opinión del resto de reutilizadores. Dejo el issue abierto para eso.

**Comment by numeroteca** [comment]
Por mi bien quitarlo. No lo uso y me obliga a filtrarlo para que no moleste.

**Comment by JJ** [comment]
No uso esos CSV, pero me parece razonable.

**Comment by ramiroaznar** [comment]
Opino igual.

**Comment by Krato** [comment]
A mi me parece bien tenerlos. Es muy util después para mostrar los datos totales. Es decir, de la otra manera habría que recorrer cada CCAA y sumar, mientras que si ya vienen pues es un paso que te ahorras.

Creo que para las gráficas es un dato muy bueno contar con los totales.

**Comment by AntonioJDios** [comment]
Desde el día 8 no hay datos para hospitalizados en totales. Es por este motivo?

**Comment by adelgadob** [comment]
Por favor, lea el Readme. Es allí donde explicamos la situación de los datos cada vez que hay un cambio metodológico por parte de Sanidad.

**Comment by AntonioJDios** [comment]
gracias!
