### ISSUE TITLE
Calidad dato nacional_covid19_rango_edad.csv

### ISSUE THREAD

**Issue by DasHammett** [datadista/datasets#42]
Me pregunto cómo de fiables son estos datos, especialmente los fallecimientos.
Entiendo que son datos acumulados, pero aun así, no parecen ser correctos.

Ejemplo:
Fallecimientos ambos sexos 25/03: 918 casos
Si es acumulado, está mal porque llevamos más de 3000 muertes, y 918 muertes en un día, no parece una cifra correcta, ya que según otra información nos movemos alrededor de los 450 diarios.

**Comment by adelgadob** [comment]
Son estadísticas de los datos que han podido determinar esa información:

Datos 2020-03-22 Datos obtenidos del análisis sobre 18.959 casos notificados con información de edad. 

Datos 2020-03-24 obtenidos del análisis sobre 20.471 casos notificados con información de edad y 20.459 con información de edad y sexo. 

Datos 2020-03-25 obtenidos del análisis sobre 21.872 casos notificados con información de edad y 21.851 con información de edad y sexo
