### ISSUE TITLE
Estabilidad de los ficheros CSV

### ISSUE THREAD

**Issue by owahltinez** [datadista/datasets#43]
Primero de todo, muchas gracias por hacer estos recursos disponibles para todos. Me parece una iniciativa estupenda.

Hasta ahora, estaba intentando analizar los ficheros PDF de la situación actual de manera automática. Por desgracia, el formato de las tablas cambia casi todos los días así que mis scripts no eran muy estables.

Puesto que uds. ya estáis haciendo esto, me parece más sencillo usar sus datos en vez de reinventar la rueda, así que ahora estoy empleando sus archivos CSV en [mi proyecto](https://github.com/open-covid-19/data).

Mi pregunta es: ¿cómo de estable es el formato y la URL de sus ficheros CSV? Añadir columnas no supone un problema, pero renombrarlas, quitarlas, o cambiar la URL de los ficheros haría que la ingestión de datos para mi proyecto fallase. Entiendo que esto es algo que hacéis de manera gratuita para el resto de nosotros, así que no espero una garantía completa, pero me gustaría saber si tienen algún mecanismo para comunicar a los usuarios de sus datos si algo va a cambiar de manera que rompa la compatibilidad de previos formatos.

**Comment by adelgadob** [comment]
En principio se van a mantener con ese formato y el nombre de los ficheros. Esta semana ya se hicieron cambios para normalizarlos. Si hacemos un cambio avisaremos previamente como issue o en el readme.
