### ISSUE TITLE
Datos de pacientes COVID-19 ingresados por hospital

### ISSUE THREAD

**Issue by jmarxuach** [datadista/datasets#47]
Hola, estoy buscando datasets de numero de pacientes pors hospital.
Sabeis donde puedo conseguirlos ? Puedo extraer datos y colgarlos en el github

Muchas gracias.

**Comment by adelgadob** [comment]
Esos datos solo lo están ofreciendo algunas CCAA como Castilla y León: https://analisis.datosabiertos.jcyl.es/pages/coronavirus/#situacin-actual

Tendrías que pedirlo a cada CCAA si no lo están ofreciendo de forma activa.
