### ISSUE TITLE
Uso de datos nacional_covid19_rango_edad.csv para ver evolución

### ISSUE THREAD

**Issue by Jordieku** [datadista/datasets#49]
Primero de todo, felicitaros por la información que estáis publicando.

Partiendo de el tiempo de incubación del virus es de 2 a 14 días, con una media de 5 días. Los datos que ofrecéis son interesantes para valorar como está funcionando el confinamiento.
Podría servirnos para ver como han crecido los datos por franjas de edad desde que comenzó el confinamiento. Distribuyendo por franjas entre los que no han podido salir de casa (0-19), los que han podido salir de casa por diversos casos (20-59), la franja entre trabajadores y jubilados (60-69) y los mayores de 70 que deberían haberse quedado en casa o solo salir para comprar, médico o pasear perro.
El primer número son los casos el 23/03/20, el segundo los casos del 27/03/20 y el tercero el incremento de casos entre las dos fechas.
0-19 años: 350 casos a 493 casos, incremento de un 40,8%
20-59: 9541 casos a 16858 casos, incremento de un 76,6%
60-69: 2916 casos a 5633 casos, incremento de un 93%
+70: 6152 casos a 11625 casos, incremento de un 83%

El incremento total sería del 80%

Los datos de los casos de cada día, son inferiores a los casos reportados en otros archivos ( p.e. el día 23/03/2020 en este archivo hay 18959 casos, mientras que oficialmente son 33089, por lo que entiendo que no se pueden utilizar para valorar como funciona el confinamiento. No sé si existe la posibilidad de que puedan coincidir los datos de los casos totales 

Además, hay la variable de que por encima de los 75 años puede haber un porcentaje importante de casos producidos en residencias.

**Comment by adelgadob** [comment]
Ese dataset lleva asociado este otro con el número de casos diarios sobre los cuales se ha realizado el análisis. https://github.com/datadista/datasets/blob/master/COVID%2019/nota_nacional_covid_19_rango_edad.csv
Solo son datos de casos confirmados en los que han podido determinar la edad y el sexo. Son los únicos datos disponibles a día de hoy.
