### ISSUE TITLE
Datos por rango de edad y sexo

### ISSUE THREAD

**Issue by AntonioJDios** [datadista/datasets#50]
Hola, solo tenemos los datos a partir del 23 de marzo no? antes de eso no se publicaban los datos? no sabemos como evoluciona la curva desde el 8 M hasta el 23 no?

gracias!! enhorabuena por el trabajo

**Comment by adelgadob** [comment]
Efectivamente. En realidad hay datos desde el 22 pero ese día publicaron ambos sexos juntos y el 23 volvieron a publicar los mismos datos desagregando por sexos. Solo hay datos a partir de ese día.

**Comment by AntonioJDios** [comment]
Que cosas... en fin. A ver si podemos encontrarlos!
