### ISSUE TITLE
Errores en los valores del fichero nacional_covid19_rango_edad.csv del 2020-04-06

### ISSUE THREAD

**Issue by robertoferrero** [datadista/datasets#59]
Se han introducido varios errores en los valores referentes al 2020-04-06 del fichero nacional_covid19_rango_edad.csv debido a valores a los que les faltan dígitos después del punto de unidades de millar.

Datos erróneos detectados:
ambos: 
40-49: hospitalizados 4.34
50-59: hospitalizados 6.84
70-79: confirmados 14.3
80-89: hospitalizados 7.79

hombres:
40-49: hospitalizados 2.62
70-79: confirmados 8.41
Total: fallecidos 3.13

**Comment by adelgadob** [comment]
Arreglado. Gracias
