### ISSUE TITLE
El dato de "acumulados hospitalizados" proporcionado por el ministerio está mal calculado, porque suma incidencia y prevalencia.

### ISSUE THREAD

**Issue by JJ** [datadista/datasets#60]
Como [ha indicado fdezordonez en Twitter, ese dato está mal](https://twitter.com/fdezordonez/status/1247498247477886977)
![Captura de pantalla de 2020-04-07 14-47-42](https://user-images.githubusercontent.com/500/78671022-f6635800-78de-11ea-959e-2f10920678b7.png)
Y ha provocado el pico en el número de hospitalizados de hoy. ¿Ese agregado lo ha proporcionado el ministerio?

**Comment by adelgadob** [comment]
Nosotros nunca modificamos los datos de las tablas. Es el dato que se incluye en la tabla de hospitalizados. 

Hasta ayer, los datos de Castilla y León eran de prevalencia, es decir, la situación en ese momento dado. A partir de hoy ese dato es el acumulado. Lo hemos confirmado con Sanidad y así lo hemos añadido al readme.

**Comment by JJ** [comment]
A ver, o está mal el dato de hoy o están posiblemente todos los demás. Porque si ayer el dato de Castilla y León era el del día, y se estaba sumando al resto de los acumulados, entonces toda la serie de datos de hospitalizados está mal.

**Comment by JJ** [comment]
A ver, ya estoy viendo de nuevo la tabla. ¿El total lo sumáis vosotros o lo proporciona el ministerio? En cualquiera caso está *mal*. Estáis sumando datos de hospitalización diarios (en algunas comunidades) con datos de hospitalización acumulados (en otras comunidades). Si el total de abajo es la suma de la columna, está mal. En particular la descripción de esa columna "Hospitalizados acumulados" en el README.md del directorio está equivocada.

**Comment by adelgadob** [comment]
El total es la suma suministrado por el Ministerio de Sanidad. Nosotros no realizamos ningún cálculo en esos datasets. Solo extraemos y normalizamos la información.

El dato de acumulado no es la suma de los datos de prevalencia. Los datos de prevalencia indica el número de personas que cada día están hospitalizados mientras que el acumulado muestra el número total de personas que han necesitado un ingreso hospitalario.

**Comment by JJ** [comment]
El dato de acumulado es la suma de toda la columna, incidencia y
prevalencia. Están sumando incidencia y prevalencia. El resultado: absurdo.

**Comment by JJ** [comment]
Y posiblemente el dato de UCI tiene el mismo problema. 
![Captura de pantalla de 2020-04-07 18-21-23](https://user-images.githubusercontent.com/500/78696000-228ed100-78ff-11ea-860f-be051b2d439d.png)
Como se ve aquí, el dato publicado para el nacional es simplemente la suma de la columna. No se intenta calcular el dato de incidencia para las comunidades donde se publica la prevalencia.

**Comment by adelgadob** [comment]
Lo mismo pasa con la ingresados UCI.

Y hay un problema más. El número acumulado entre una fecha y otra no significa la diferencia en el número de casos nuevos ese día, ya que pueden haberse incluido datos recuperados de fechas anteriores. Es algo que ha sucedido hoy con el número de fallecidos. incluye fallecidos en fin de semana que no se notificaron hasta ayer en algunas CCAA.

**Comment by JJ** [comment]
Conclusión: vamos a dejar de usar los datos oficiales del ministerio de
Sanidad para absolutamente nada porque son inútiles.

**Comment by JJ** [comment]
Mientras corrigen, propongo que simplemente borréis esas dos columnas del fichero como protesta. A ver si se dan cuenta de que no están haciendo las cosas bien.

**Comment by chatox** [comment]
Yo creo que en tal caso la fila "Total" no debería aparecer en el fichero, e idealmente en el hospitalizados_long tendría que haber una columna "tipo" que indicara si para esa fecha es "prevalencia" o "incidencia".

**Comment by JJ** [comment]
El mié., 8 abr. 2020 a las 11:56, Carlos Castillo (<notifications@github.com>)
escribió:

> Yo creo que en tal caso la fila "Total" no debería aparecer en el fichero,
> e idealmente en el hospitalizados_long tendría que haber una columna "tipo"
> que indicara si para esa fecha es "prevalencia" o "incidencia".
>
Me parece correcto.

**Comment by adelgadob** [comment]
Desde hoy no se incluyen los totales. Ayer hablamos con Sanidad y le expresamos que no debería sumarse prevalencia y acumulados. Las notas sobre las CCAA que muestran prevalencia y acumulados están en el Readme. Vamos actualizando estas notas cada vez que se producen. Vamos a incluir un nuevo dataset accesorio de metadatos con esta información.

**Comment by chatox** [comment]
@adelgadob gracias. Te cuento que estoy usando estos datos para actualizar [estas tablas](https://en.wikipedia.org/wiki/Template:2019%E2%80%9320_coronavirus_pandemic_data/Spain_medical_cases) y [estos gráficos](https://en.wikipedia.org/wiki/2020_coronavirus_pandemic_in_Spain#Charts_based_on_daily_reports) en la Wikipedia.

**Comment by JJ** [comment]
> Desde hoy no se incluyen los totales. Ayer hablamos con Sanidad y le expresamos que no debería sumarse prevalencia y acumulados. Las notas sobre las CCAA que muestran prevalencia y acumulados están en el Readme. Vamos actualizando estas notas cada vez que se producen. Vamos a incluir un nuevo dataset accesorio de metadatos con esta información.

¿Y lo entendieron?

**Comment by JJ** [comment]
En todo caso, el error es de la serie completa. Está bien que no lo
incluyáis a partir de hoy para llamar la atención, pero el error viene de
atrás...

**Comment by adelgadob** [comment]
Según Sanidad, en unos días la serie de acumulados en hospitalizados e ingresos UCI estará completa y disponible.
