### ISSUE TITLE
No hay cálculo de totales en dos ficheros para el día 2020-04-08

### ISSUE THREAD

**Issue by odoral** [datadista/datasets#61]
En los ficheros ccaa_covid19_hospitalizados.csv y ccaa_covid19_uci.csv no hay cálculo de totales para el día de hoy:

**ccaa_covid19_hospitalizados.csv**:
![image](https://user-images.githubusercontent.com/779829/78812020-0e180a80-79cb-11ea-88f9-a10059bae0a0.png)

**ccaa_covid19_uci.csv**
![image](https://user-images.githubusercontent.com/779829/78812165-44ee2080-79cb-11ea-8b50-6ae25d089a65.png)

**Comment by odoral** [comment]
Acabo de leer el readme con el cambio de hoy.

Una pena no disponer de un dato globalizado.

**Comment by JJ** [comment]
Ese dato "globalizado" no ha existido nunca. Han estado sumando cosas
diferentes. Ayer se dieron cuenta y hoy no lo han publicado, pero los datos
de antes tenían el mismo problema.

**Comment by odoral** [comment]
Lo dicho, una pena no tener datos normalizados a ámbito nacional. Y por favor, que nadie se tome esto como un menosprecio al valor del repo.

Muchas gracias a quien corresponda.

**Comment by JJ** [comment]
De hecho, gracias a la gente detrás del repo se dejó de publicar un dato patentemente falso.
