### ISSUE TITLE
Dato de hospitalizados de Castilla La Mancha erróneo (2020-04-12)

### ISSUE THREAD

**Issue by cesarperezalvarez** [datadista/datasets#62]
Hola,
el dato de Castilla La Mancha de hoy parece erróneo. Hay un comentario en el archivo de hospitalizados de hoy que no logro entender. Se refiere a que han cambiado la forma de contabilizar o es que el dato está erróneo.

Gracias!!!

**Comment by adelgadob** [comment]
Sí, se ha cambiado la forma de medir. Está explicado en el comentario del commit y en el Readme. Eran datos de prevalencia, es decir, la situación diaria y han pasado a ser datos acumulados.
