### ISSUE TITLE
¿Inconsistencia entre informe 77 del 16.04.2020 e informe 78 del 17.04.2020?

### ISSUE THREAD

**Issue by chatox** [datadista/datasets#65]
La cifra de nuevos recuperados y fallecidos entre el informe 77 y el informe 78 no corresponde con las cifras en esos informes.

* El informe 77 indica 19140 fallecidos y 74797 recuperados.
* El informe 78 indica 19478 fallecidos (585 nuevos) y 72963 recuperados (3502 nuevos).

Pero si hacemos la resta entre los dos informes debiesen ser 338 nuevos fallecidos (no 585) y un número negativo de recuperados. ¿Alguien sabe de dónde proviene esta anomalía? Gracias.

**Comment by adelgadob** [comment]
Por favor, leed el Readme. Allí incluimos todas las nuevas notas diarias.

**Comment by chatox** [comment]
Sorry! Cuidaré de mirarlo antes de preguntar la próxima vez. Gracias.
