### ISSUE TITLE
Total altas

### ISSUE THREAD

**Issue by CarlosLannister** [datadista/datasets#67]
| fecha | cod_ine | CCAA | total
-- | -- | -- | -- | --
  | 2020-04-16 | 00 | Total | 74797
  | 2020-04-17 | 00 | Total | 72963

El día 16 hay un número mayor de altas totales que las del 17. Esto no cuadra por algún lado. 

https://github.com/datadista/datasets/blob/master/COVID%2019/ccaa_covid19_altas_long.csv

**Comment by adelgadob** [comment]
Por favor, leed el Readme. Allí actualizamos todas las notas. Gracias.
