### ISSUE TITLE
Dato de Fallecidos de Navarra Erróneo

### ISSUE THREAD

**Issue by cesarperezalvarez** [datadista/datasets#68]
El dato de Navarra es 77? Si vemos la serie histórica pareciera que hay un 7 más.  El dato nacional de 585 que dice el ministerio está bien?

**Comment by cesarperezalvarez** [comment]
Parece que cambiaron la metodología https://www.diariodenavarra.es/noticias/navarra/2020/04/17/ocho-nuevos-fallecidos-elevan-348-los-muertos-por-coronavirus-navarra-687583-300.html

**Comment by adelgadob** [comment]
¿Puedes especificar dónde has visto ese dato de 77? Gracias

**Comment by cesarperezalvarez** [comment]
La diferencia entre el dato del día 17 y 16 de abril para navarra en el archivo ccaa_covid19_fallecidos.csv  es 77 cuando generalmente andaba por los 7 u 8. Leyendo la noticia que coloqué en el otro comentario, lo que creo es que Navarra ha cambiado la forma de reportar.

**Comment by adelgadob** [comment]
A Sanidad solo reportan el dato de muertes confirmadas con un test diagnóstico realizado. Por favor, lea el Readme donde explicamos los últimos cambios metodológicos y rupturas de las series.
