### ISSUE TITLE
PDF resumen de situación que faltan

### ISSUE THREAD

**Issue by FcoJavT** [datadista/datasets#7]
Hola, aporto los PDF Actualizacion_42B_COVID-19_18.00 y Actualizacion_41B_COVID-19_18.00, que faltan en la carpeta.
Tambien tengo toda la serie del 2 al 20, pero no sé si la quieres.
Muchas gracias.
[Actualizacion_41B_COVID-19_18.00.pdf](https://github.com/datadista/datasets/files/4332847/Actualizacion_41B_COVID-19_18.00.pdf)
[Actualizacion_42B_COVID-19_18.00.pdf](https://github.com/datadista/datasets/files/4332848/Actualizacion_42B_COVID-19_18.00.pdf)

**Comment by adelgadob** [comment]
Sí, por favor, compártelas para actualizar la carpeta. ¡Gracias!
