### ISSUE TITLE
fecha duplicada

### ISSUE THREAD

**Issue by hmeleiro** [datadista/datasets#71]
Hola, gracias por el currazo.

He visto que en la fila de hoy en el archivo `nacional_covid19.csv` los datos de hoy viene con la fecha de ayer, lo que significa que hay dos filas con una misma fecha. No es un problema grave, pero para que lo sepáis.

<img width="525" alt="Captura de pantalla 2020-04-21 a las 11 34 48" src="https://user-images.githubusercontent.com/29704914/79850536-60dac480-83c4-11ea-9f24-3d37a83d82f0.png">

Un saludo.

**Comment by adelgadob** [comment]
Arreglado. Gracias
