### ISSUE TITLE
creo que en los casos nuevos has puesto los datos de altas para el dia 22 de abril

### ISSUE THREAD

**Issue by MegeaPortalSQL** [datadista/datasets#73]
coincide el número y parece un bug

**Comment by adelgadob** [comment]
Lo hemos solucionado hace 2 minutos. Gracias por el aviso.

**Comment by MegeaPortalSQL** [comment]
> Lo hemos solucionado hace 2 minutos. Gracias por el aviso.

Gracias, y gracias por el esfuerzo de recopilarlo.
