### ISSUE TITLE
ICU admissions

### ISSUE THREAD

**Issue by CarloLucibello** [datadista/datasets#74]
Does anyone know if the ICU admissions data exists somewhere for Spain? I'm not talking about ICU current occupation, but the daily number of new entrances in ICU

**Comment by adelgadob** [comment]
Only madrid and galicia publish daily prevalence data

**Comment by CarloLucibello** [comment]
thanks! can you point me to the sources?

**Comment by adelgadob** [comment]
https://github.com/datadista/datasets/blob/master/COVID%2019/ccaa_covid19_uci.csv
https://github.com/datadista/datasets/blob/master/COVID%2019/ccaa_covid19_uci_long.csv

**Comment by CarloLucibello** [comment]
isn't that current occupation?

**Comment by adelgadob** [comment]
Please, read the table "(**)COMUNIDADES AUTÓNOMAS QUE PUBLICAN DATOS DE PREVALENCIA" in Readme.md

**Comment by CarloLucibello** [comment]
Thanks again. Sorry to pester you, but this seems a bit weird. According to France hospitalization data https://www.data.gouv.fr/fr/datasets/r/6fadff46-9efd-4c53-942a-54aca783c30c
the icu daily admissions (column incid_rea) for the whole France peaked to a value <1000 at the end of march and are below 200 these days. 
On the other hand, from 
https://github.com/datadista/datasets/blob/master/COVID%2019/ccaa_covid19_uci_long.csv
it seems that Madrid alone peaked at 1500 at the end of march and it's still at ~1000 admissions. These numbers seem a bit large. Are you entirely sure that they represent admissions and not current occupation for Madrid?  Sorry again for bothering but I'm desperately looking for admission data to test a model and don't want to make such mistakes

**Comment by CarloLucibello** [comment]
ok, now I understand, I should look to everything that is *not* Madrid or Galicia. thanks again
