### ISSUE TITLE
Indicar la fuente para el dato publicado de : Número de TEST realizados

### ISSUE THREAD

**Issue by JJGP00** [datadista/datasets#76]
Revisando fuentes y tablas csv, no encuentro de dónde sale el dato (27/04/2020) de 1.200.000 test realizados. Las fuentes del ministerio indican 220.000 aprox. ¿Pueden aclarar este punto? gracias

**Comment by adelgadob** [comment]
Acabamos de publicar este dataset. Sanidad ha publicado hoy por primera vez estos datos.
