### ISSUE TITLE
Error en casos de Navarra (27/04/2020)

### ISSUE THREAD

**Issue by Krato** [datadista/datasets#77]
Hola buenas.

He estado revisando y los datos de Navarra para hoy (27/04/2020) no parecen correctos. 

Los casos han pasado de 5452 (ayer) a 12263 (hoy).

Me he fijado porque al ir a revisar las cifras en mi web, de repente he visto un salto sustancial y he investigando.

Por cierto y aparte. Si queréis pódeis incluir mi web en vuestro listado: https://covid19esp.herokuapp.com.

Un saludo y gracias por el trabajo

**Comment by adelgadob** [comment]
Hola, Krato, estamos intentando chequearlo con una fuente oficial. El dato proviene del CSV del ISCIII de los datos de test de anticuerpos. Pasa de 740 de ayer a 7530 hoy. Pensamos que se les puede haber escapado un cero.

**Comment by Krato** [comment]
Jajaja es probable. Gracias por avisar :D

**Comment by Krato** [comment]
@adelgadob Mientras tanto, no valdría la pena poner el resultado "probable" hasta que confirmen del ministerio? Ya que sería muy raro. Gracias

**Comment by adelgadob** [comment]
Corregidos. Nos ha confirmado Sanidad que era un error.
