### ISSUE TITLE
Fecha 27/04: No coincide nº de casos ni curados con Sanidad por 20.000 

### ISSUE THREAD

**Issue by JJGP00** [datadista/datasets#79]
En el informe de hoy de Sanidad se hace constar que hay 20.000 casos totales menos de los que figuran en la web (229K worldometer 209K Ministerio). También figuran 20.000 curados más (120K worldometer 100K ministerio)

**Comment by adelgadob** [comment]
Era debido a que Sanidad empezó a dar como casos confirmados solo los confirmados por PCR. En los datasets tienes ambas series.
