### ISSUE TITLE
Los datos de altas de Madrid del 28/04 no son correctos

### ISSUE THREAD

**Issue by LauFoto** [datadista/datasets#81]
Deberían ser 35841
![image](https://user-images.githubusercontent.com/50845205/80475197-d1478f80-8948-11ea-90c4-672a573aa9b6.png)

Pero en el fichero de altas vienen 55841
![image](https://user-images.githubusercontent.com/50845205/80475133-b5dc8480-8948-11ea-8f02-b47903cb7088.png)

**Comment by adelgadob** [comment]
Solucionado. Gracias por avisar.
