### ISSUE TITLE
29/04 Galicia Fallecidos

### ISSUE THREAD

**Issue by emunozlorenzo** [datadista/datasets#84]
El dato de Galicia de fallecidos asciende a 135 fallecidos en el día de hoy ¿Es esto correcto?

**Comment by fyedro** [comment]
Tengo la misma duda. Según los datos son 135 pero se están contabilizando como 7, ¿se debe a que se han incluido hoy datos anteriores sin contabilizar? Porque, además, el dato de fallecidos de ayer era 23822 y el de hoy 24275, lo que serían 453 de incremento, no 325 (entiendo que este dato lo obtienen contando solo 7 a Galicia).

**Comment by adelgadob** [comment]
Por favor, leed siempre el Readme donde incluimos las notas diarias. Los casos de Galicia nuevos respecto ayer son 7, pero Galicia ha notificado 128 casos de días anteriores que Sanidad ha decidido sumar en el total nacional.
