### ISSUE TITLE
Diferencia nuevos casos y total casos

### ISSUE THREAD

**Issue by emiliop37** [datadista/datasets#85]
Los nuevos casos de hoy miércoles 29 ascienden a casi 4.800, más del doble que las cifras de Sanidad (menos de 2.200).
Los casos totales de infectados superan los 236.000, mientras que los datos de Sanidad no alcanzan los 213.000.
A que se debe esa nada despreciable diferencia?
Gracias.

**Comment by adelgadob** [comment]
Le recomiendo que antes de abrir un issue lea el Readme y lo que significa los datasets que se utilizan. 236.00 son casos totales y los 213.000 son casos confirmados por PCR.
