### ISSUE TITLE
wrong number of cases and recored in spain

### ISSUE THREAD

**Issue by hugodealfredo** [datadista/datasets#87]
the government declared the following numbers as the official ones for the covid-19 in Spain. 
Total cases: 213435
Recovered: 112050
Dead: 24543

There are two links that prove this data:
https://covid19.isciii.es/
https://www.mscbs.gob.es/profesionales/saludPublica/ccayes/alertasActual/nCov-China/documentos/Actualizacion_91_COVID-19.pdf

Can you please change them because they use your wrong data in the worldometer web.

**Comment by adelgadob** [comment]
Hi Hugo, please, read Readme.md. Column "Casos" in nacional_covid19.csv are "Accumulated total confirmed cases (PCR + Antibody test)"

**Comment by msalaslo** [comment]
Hola @adelgadob,  entiendo que has declarado los test de anticuerpos a worldometers.info. Si se incluyen estos datos ¿son comparables las cifras de contagios con las de otros países?

**Comment by adelgadob** [comment]
Nosotros no estamos en contacto con la gente de worldometers. Explicamos a todos los reutilizadores en inglés y español la descripción de los datasets principales en el Readme. En este issue puede ver los cambios que hemos planteado en ese y otros datasets. Se va a incluir dos columnas con los casos PCR y testAC: https://github.com/datadista/datasets/issues/48#issuecomment-621954002
