### ISSUE TITLE
No coincide el número de test realizados

### ISSUE THREAD

**Issue by ricardopch** [datadista/datasets#88]
Hola, he visto que el número total de test realizados para España que figura en la tabla de países de la web (1.455.306), no coincide con el total que aportas (1.345.560) en el dataset **ccaa_covid19_test_realizados.csv**

¿Sabes si hay alguna otra fuente que no esté teniendo en cuenta?
Gracias.
![image](https://user-images.githubusercontent.com/64636498/80796673-2204f580-8ba0-11ea-83d5-d98c189cab4b.png)

![image](https://user-images.githubusercontent.com/64636498/80796644-08fc4480-8ba0-11ea-92ad-1352b0f49fda.png)

**Comment by adelgadob** [comment]
Puede que estén agregando datos publicados por algunas CCAA de forma independiente.
