### ISSUE TITLE
Hay 2 ficheros duplicados

### ISSUE THREAD

**Issue by persep** [datadista/datasets#90]
Hay un fichero con nombre:

`COVID 19/ccaa_covid19_UCI.csv`

con datos hasta el 1-mayo y otro con:

`COVID 19/ccaa_covid19_uci.csv`

Con datos hasta el 30-abril
Creo que lo mejor es unificarlo en uno solo con un nombre todo en minúsculas.

**Comment by adelgadob** [comment]
Gracias, ha sido un error al subir la nueva serie. Ya ha sido solucionado.
