### ISSUE TITLE
Inconsistencia en los casos confirmados

### ISSUE THREAD

**Issue by melon-boy** [datadista/datasets#95]
Si sumas la última columna, 05-05-2020, de todas las comunidades, obtienes el valor de 250.561 casos. No obstante, según los datos oficiales son algo más de 219.000.

**Comment by adelgadob** [comment]
Por favor, antes de abrir un issue lea el Readme y la información que ofrece cada dataset. Está mezclando casos totales (PCR+TestAC) con casos confirmados por PCR.

**Comment by josejoa** [comment]
> 
> 
> Si sumas la última columna, 05-05-2020, de todas las comunidades, obtienes el valor de 250.561 casos. No obstante, según los datos oficiales son algo más de 219.000.

Lo acabo de sumar en el último informe del Ministerio de Sanidad y da 220.325 justos.
https://www.mscbs.gob.es/profesionales/saludPublica/ccayes/alertasActual/nCov-China/documentos/Actualizacion_97_COVID-19.pdf

**Comment by josejoa** [comment]
> 
> 
> Por favor, antes de abrir un issue lea el Readme y la información que ofrece cada dataset. Está mezclando casos totales (PCR+TestAC) con casos confirmados por PCR.
Lo que no entiendo es porque en https://www.worldometers.info/coronavirus/
para unos países ponen los casos totales por PCR y en otros suman los de PCR y los TestAC, se han hecho un lío monumental. Y en otras columnas todavía es peor, con los recuperados y los críticos.
