### ISSUE TITLE
Uso de separadador de miles inconsistente

### ISSUE THREAD

**Issue by pareyesv** [datadista/datasets#96]
Apareció un delimitador de miles en los datos que crea inconsistencias con los datos anteriores:

https://github.com/datadista/datasets/blob/32eae6af5463a880f6ae41d171fd19b66dc1f1fb/COVID%2019/nacional_covid19_rango_edad.csv#L1453

comparado con el día anterior
https://github.com/datadista/datasets/blob/32eae6af5463a880f6ae41d171fd19b66dc1f1fb/COVID%2019/nacional_covid19_rango_edad.csv#L1419

NOTA: No he revisado en qué otros ficheros está ocurriendo.

Por cierto: aprovecho de agradecer el trabajo! :clap:

**Comment by adelgadob** [comment]
Solucionado. Muchas gracias
