### ISSUE TITLE
Missing province column in case data

### ISSUE THREAD

**Issue by rneher** [datadista/datasets#98]
We are using your data for covid19-scenarios but have had some trouble recently. 

The hospitalization and ICU data for Madrid has a strange jump around April 26. See this file:

https://github.com/datadista/datasets/blob/master/COVID%2019/ccaa_covid19_hospitalizados.csv

The case data file
https://github.com/datadista/datasets/blob/master/COVID%2019/ccaa_covid19_casos.csv
no longer has CCAA as second column. Other files still do. Do we need to adapt our parsers, or is this a bug?

thanks a lot, you have a terrific data source here!

**Comment by adelgadob** [comment]
Fixed. Thanks!

**Comment by rneher** [comment]
That was fast! thanks! And the hospitalizations for Madrid are actually correct?

**Comment by rneher** [comment]
I am referring to this jump from ~6000 to ~40000 in one day:
![image](https://user-images.githubusercontent.com/8379168/81315901-3444cf00-908b-11ea-956d-56206e3ae920.png)

**Comment by rneher** [comment]
second to last row in the screen grab

**Comment by adelgadob** [comment]
Please, look this table in Readme "(**)COMUNIDADES AUTÓNOMAS QUE PUBLICAN DATOS DE PREVALENCIA" Madrid until 2020-04-26 published prevalence data.

**Comment by rneher** [comment]
thanks.
